Repository MathisFederico/LearnRL, pull requests merged in 2020-11, with the labels that each got.

#79 Feature/callbacks/wandb
  learnrl/callbacks/__init__.py
  learnrl/callbacks/tensorboard.py
  learnrl/callbacks/wandb.py
  requirements-dev.txt
  tests/conftest.py
  tests/tests_callbacks/test_tensorboard.py
  tests/tests_callbacks/test_wandb.py
Labels: enhancement

#80 Feature/handlers logs
  learnrl/callbacks/tensorboard.py
  learnrl/playground.py
Labels: enhancement

#65 Add cartpole example for DQN
  README.rst
  examples/cartpole/README.md
  examples/cartpole/cartpole.py
Labels: documentation

#89 Added custom metrics args support in pg.run
  learnrl/callbacks/logger.py
  learnrl/playground.py
Labels: documentation, enhancement

#97 Feature/step cycle
  examples/cartpole/README.md
  learnrl/callbacks/callback.py
  learnrl/callbacks/logger.py
  learnrl/callbacks/logging_callback.py
  learnrl/callbacks/tensorboard.py
  learnrl/callbacks/wandb.py
  learnrl/playground.py
  tests/unit/callbacks/test_logging.py
Labels: enhancement
